### PR TITLE
fix(hdiutil): fixed detach error check

### PR DESCRIPTION
**Pull request by blyork**
Fix for issue #142 
Added check for err.code
Added 5 attempts with backoff.

### CODE REVIEW

**Comment by alexpelan** [comment]
I'd be glad to lend a hand to get this merged and released

**Comment by LinusU** [comment]
@alexpelan have you tested this? ☺️ if anyone can confirm that it works that would be great

**Comment by alexpelan** [comment]
Yeah, I patched this on my machine and it's working fine, unblocked me. I haven't ever reached the attempts > 5 boundary where it terminates, but I've definitely seen the backoff and future attempts succeeding. It seems like it fails exactly once for me every time 🤷

**Comment by alexswilliams** [comment]
Can confirm this commit also solves the problem perfectly for me - exactly as alex said, seemed to retry once :)

**Comment by elliottkember** [comment]
I just hit the `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` error referenced above in an OSX 11.0 GitHub action. This looks like a good workaround - who has write access and could merge this in?

**Comment by jjcoffman** [comment]
Is there anyone with the powers to get this in and cut a new release?

**Comment by joanx** [comment]
We're also seeing this issue, confirmed this fix works, and would love to expedite this however we can.

**Comment by LinusU** [comment]
@joanx thanks for confirming that the fix works 👍 

Released as [🚢 0.6.1 / 2021-07-07](https://github.com/LinusU/node-appdmg/releases/tag/v0.6.1)

**Comment by dmahieuDos** [comment]
Sorry to reopen this, but there is still an issue in that patch.
I've got a French version of OsX and /Resource busy/.test(err.stderr) test fails because message is partially translated (hdiutil: couldn't unmount "disk9" - Ressource occupée\n).

hdiutil returns EBUSY (16) on "Resource busy", then don't think it's needed to add Ressource busy test (redundant with err.code === 16).

**Comment by pzhlkj6612** [comment]
Hi, @dmahieuDos . Please see #200 and upvote it.

**Pull request merged**
