### PR TITLE
Let optionally use alternate volume icon

### PR DESCRIPTION
**Pull request by guidograzioli**
Very small change that lets to optionally specify an alternate icon in the json config, to be used as the volume icon.

### CODE REVIEW

**Comment by LinusU** [comment]
I might be missing something here but why don't you just specify `icon`, why do you need to ways to specify it?

**Comment by guidograzioli** [comment]
My requirement is to have two different icons, one as the volume icon (which appears on the desktop after mounting the dmg), a different one the appears in the main windows (to be dragged to Applications). If there is another way to do that, sorry I did not notice it, feel free to close the pull.

screenshot from 2015-05-13 17 41 33

**Comment by LinusU** [comment]
The `icon` option dosen't affect any of the files in the `contents` array.

Use the `icon` option to set the volume icon, and use normal means to set the file icon. One way is to right click the `.app`, select `Get Info` and then drag a new icon on top of the old one.

**Comment by guidograzioli** [comment]
Is it possible to specify the icon file to use in the json contents? or is it using the icon in Content/Resources for the .app? appdmg is setup to run remotely, in a ssh session to a vm running osx, as a postbuild step in jenkins.

**Comment by LinusU** [comment]
Appdmg dosen't do anything besides copying in the entire file/directory specified. Does your `.app` file have the wrong icon from the beginning?

I think that the best place to solve this would be in the process that spits out the `.app` file. If you are building with XCode you can just change it in the project.

If that's not an option then maybe this can help you: http://superuser.com/questions/618501/changing-an-applications-icon-from-the-terminal-osx

**Pull request closed without merging**
